apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: qr-attendance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: qr-attendance-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: qr-attendance-config
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: qr-attendance-config
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qr-attendance-secret
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: qr-attendance-secret
                  key: SECRET_KEY
            - name: ADMIN_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: qr-attendance-config
                  key: ADMIN_USERNAME
            - name: ADMIN_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: qr-attendance-config
                  key: ADMIN_EMAIL
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qr-attendance-secret
                  key: ADMIN_PASSWORD
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: qr-attendance-secret
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: qr-attendance-secret
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: qr-attendance-secret
                  key: CLOUDINARY_API_SECRET
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
