apiVersion: v1
kind: ConfigMap
metadata:
  name: qr-attendance-config
  namespace: qr-attendance
data:
  POSTGRES_DB: qr_attendance
  POSTGRES_USER: qruser
  ADMIN_USERNAME: admin
  ADMIN_EMAIL: admin@qrattendance.com
